baseurl = "https://sylcha.github.io/"
contentdir = "content/google_classroom_doc/"
languageCode = "fr-fr"
title = "Utiliser Google Classroom"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Sylvain"
	description = "Une documentation sur Google Classroom pour démarrer rapidement sa classe virtuelle."
	copyright = "Released under the CC-BY-NC-SA-4.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/sylcha/"

	version = "1.0.0"
	logo = "images/profil_image.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "light green"

    [params.font]
    	text = "Dosis"
    	code = "Dosis Mono"


[social]
	twitter = ""
	github  = "sylcha"


[[menu.main]]
	name   = "Début"
	url    = ""
	weight = 0

[[menu.main]]
	name   = "Créer une classe virtuelle"
	url    = "creation/"
	weight = 10

[[menu.main]]
	name   = "Publier une information"
	url    = "messages/"
	weight = 20

[[menu.main]]
	name   = "Poser une question"
	url    = "questions/"
	weight = 30

[[menu.main]]
	name   = "Créer, gérer un devoir"
	url    = "devoirs/"
	weight = 40


[[menu.main]]
	name   = "Licence"
	url    = "licence/"
	weight = 50

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
	hrefTargetBlank = true
